### ISSUE TITLE
Events List Page

### ISSUE THREAD

**Issue by matt-paul** [CodeYourFuture/cyf-react#92]
Create Events List page as per Jun designs

Small
https://app.zeplin.io/project/5a5cb60881a36286ae95c84a/screen/5a5e2a5bc12cee72a8d12e98

Medium
https://app.zeplin.io/project/5a5cb60881a36286ae95c84a/screen/5a5e2a5cdd6d876f248319d6

Large
https://app.zeplin.io/project/5a5cb60881a36286ae95c84a/screen/5a5e2a5bd9c52bce0d37b5dd

**Comment by lani-s** [comment]
**As a**  potential/mentor
**I want**  to view a list of upcoming classes
**So that** I can identify classes I want to participate in

--------------------
**Acceptance Criteria**
- [ ] user can see page title (events)
- [ ] user can see date heading
- [ ] user can see current classes nested under date
- [ ] user can see class group
- [ ] user can see class title
- [ ] user can see class venue
- [ ] user can see class time
- [ ] user can click on view event to go to the event page
- [ ] user can see number of attendees

---------------------
**What problem we are trying to solve?**
The sign-up process for mentors is slow and manual, and attendance can vary from event to event due to no **visibility of attendees**; as a result some events can have too many mentors, some too few. 

Design for mobile view (mvp): https://app.zeplin.io/project/5a5cb60881a36286ae95c84a/screen/5a5e2a5bc12cee72a8d12e98
