### ISSUE TITLE
Single Event Page

### ISSUE THREAD

**Issue by matt-paul** [CodeYourFuture/cyf-react#93]
blah

**Comment by lani-s** [comment]
**As a**  potential/mentor
**I want**  to view upcoming class details
**So that**  so that I know what the class will cover and can show others that I am attending

--------------------
**Acceptance Criteria**
- [ ] user can see class title
- [ ] user can see subheading showing class number (as part of course)
- [ ] user can see date of class
- [ ] user can see venue of class
- [ ] user can see mentors already attending (number of & name of attendees)
- [ ] user can view description of class
- [ ] user has option to say they are attending class
- [ ] if user confirms attendance the attendance list is updated
- [ ] user can navigate back to events listing

--------------------
**What problem we are trying to solve?**
The sign-up process for mentors is slow and manual, and attendance can vary from event to event due to no visibility of attendees; as a result some events can have too many mentors, some too few.

**Comment by matt-paul** [comment]
this was completed in #109
